language: cpp
dist: bionic
os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - "python"
      - "python-pip"
#      - "python3"
#      - "python3-pip"

# jobs:
#   fast_finish: true
#   include:
#     - os: linux
#       dist: bionic
#       addons:
#         apt:
#           packages:
#             - "python3"
#             - "python3-pip"

#     - os: osx
#       osx_image: xcode11
#       addons:
#         homebrew:
#           packages:
#           - conan
#           - cmake

#   allow_failures:
#     - os: osx

install:
  - python --version
  - pip --version
#  - python3 --version
#  - pip3 --version
# Install conan
  - pip install conan
  - which conan
  - conan --version
  - conan user
# install cmake 3.17
# recipe adopted from https://cliutils.gitlab.io/modern-cmake/chapters/intro/installing.html
#  - mkdir -p cmake-3.15 && wget -qO- "https://cmake.org/files/v3.15/cmake-3.15.3-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.15; export PATH=$(pwd)/cmake-3.15/bin:$PATH
  - mkdir -p cmake-3.17 && wget -qO- "https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.17; export PATH=$(pwd)/cmake-3.17/bin:$PATH
  - which cmake
  - cmake --version
script:
   - cmake -Bbuild -H.
   - CTEST_OUTPUT_ON_FAILURE=1 make -C build all test
