language:
  - python
  - cpp

git:
  depth: false

matrix:
  fast_finish: false
  include:
    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
          sources:
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
            - key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
          sources:
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
            - key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

    - os: osx
      osx_image: xcode10.3
      language: cpp
      addons:
        homebrew:
          packages:
          - conan
          - cmake

    - os: osx
      osx_image: xcode11
      language: cpp
      addons:
        homebrew:
          packages:
          - conan
          - cmake

  allow_failures:
    - os: osx

install:
# Install conan
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update       ; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install conan; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install conan; fi
# Automatic detection of your arch, compiler, etc.
  - which conan
  - conan user
script:
   - cmake --version
   - cmake -Bbuild -H.
   - make -C build all test
