language:
  - python
  - cpp

matrix:
  fast_finish: false
  include:
    - os: linux
      dist: bionic
      compiler: clang

    - os: linux
      dist: bionic
      compiler: gcc

    - os: osx
      osx_image: xcode10.3
      language: cpp

    - os: osx
      osx_image: xcode11
      language: cpp

  allow_failures:
    - os: osx

install:
# Install conan
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install conan; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install conan; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./script/setup-cmake-ppa.sh; fi
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
   - cmake --version
   - cmake -Bbuild -H.
   - make -C build all test
